name: CI CD IOS
on:
 push:
  branches:
   - main
   - workflow_dispatch
 pull_request:
  branches:
   - main
jobs:
 build-and-test:
  runs-on: macos-latest
  steps:
  - uses: actions/checkout@v2
  - name: Select Xcode
    run: sudo Xcode-select -switch /Applications/Xcode_14.3.1.app
  - name: list
    run: ls && ls GHActionExemple.xcodeproj
  - name: Build & Test
    run: xcodebuild clean build test -workspace ./GHActionExemple.xcodeproj/project.xcworkspace -scheme GHActionExemple -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4'
